version: "3.5"
services:
  database:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3306:3036
    environment:
      MYSQL_ROOT_PASSWORD: RootPassword
      MYSQL_DATABASE: Backoffice
      MYSQL_USER: MainUser
      MYSQL_PASSWORD: MainPassword
    volumes:
      - db-volume:/var/lib/mysql
volumes:
  db-volume:


